version: 1.0.{build}
install:
- gem install bundler --no-ri --no-rdoc
- bundle install
build_script:
- rake
test: off
artifacts:
- path: build\pkg\DotNetZip.*.nupkg
  name: Nuget Package
deploy:
- provider: NuGet
  api_key:
    secure: M7LFZYxeE65s2U7APTgVFyzBDEiE5LFVFIf+d3ahGxgylxrctFcFJx9cmnamH30f
  skip_symbols: true
  artifact: /.*\.nupkg/
